#' Write a README into an output folder
#'
#' Outputs land on a shared drive where collaborators and the data custodian
#' will open them without ever seeing the pipeline. A file named
#' `outcomes_by_ethnicity.docx` does not say which cohort it describes, which
#' models produced it, when it was generated, or which caveats travel with it.
#' This puts that next to the artefact.
#'
#' Everything is derived from the objects that produced the outputs, so the
#' README cannot drift from them. Nothing here should be hand-edited: edit the
#' target that supplies it instead.
#'
#' The caveats argument is the part that earns the file. Interpretation notes
#' that live only in the methods document are the ones that get lost when
#' someone pastes a figure into a slide deck.
#'
#' @param path folder to write into
#' @param title short heading for the folder
#' @param description one paragraph on what the folder contains
#' @param files character vector of file paths produced in this folder; listed
#'   by basename so the README does not carry the full network path
#' @param population_label human-readable population name, or NULL
#' @param n analysed sample size for that population, or NULL
#' @param data_hash short hash of the analysis dataset, so two folders can be
#'   compared for provenance without opening anything
#' @param caveats character vector of interpretation notes specific to this
#'   folder
#' @param methods_path relative path to the methods document
#' @param filename README name
#'
#' @return the written file path
write_output_readme <- function(path,
                                title,
                                description,
                                files = character(0),
                                population_label = NULL,
                                n = NULL,
                                data_hash = NULL,
                                caveats = NULL,
                                methods_path = "methods.md",
                                filename = "README.md") {

  dir.create(path, showWarnings = FALSE, recursive = TRUE)
  full_path <- file.path(path, filename)

  ln <- c(
    paste("#", title),
    "",
    "This file is generated by the analysis pipeline. Do not edit it: any",
    "change will be overwritten the next time the outputs are rebuilt.",
    "",
    description,
    ""
  )

  if (!is.null(population_label)) {
    ln <- c(ln, "## Population", "",
            paste0("- ", population_label,
                   if (!is.null(n)) paste0(" (n = ", n, ")") else ""),
            "")
  }

  if (length(files)) {
    ln <- c(ln, "## Files", "",
            paste0("- `", sort(basename(files)), "`"), "")
  }

  if (length(caveats)) {
    ln <- c(ln, "## Read before using these", "",
            paste0("- ", caveats), "")
  }

  ln <- c(ln,
          "## Provenance", "",
          paste0("- Generated: ",
                 format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z")),
          if (!is.null(data_hash))
            paste0("- Analysis dataset hash: `", data_hash, "`"),
          paste0("- Full methods: `", methods_path, "`"),
          "",
          "The dataset hash identifies the version of the analysis data these",
          "outputs were built from. Two folders with the same hash were built",
          "from identical data; two with different hashes were not, and their",
          "numbers should not be quoted together.",
          "")

  writeLines(ln, full_path)
  full_path
}


#' Standing caveats for each output folder
#'
#' Held in one place so the same wording appears wherever a caveat applies, and
#' so adding a caveat is a single edit rather than a search through target
#' definitions. Keyed by folder kind.
#'
#' @param kind folder kind: "tables", "plots", "regression", "daoh", "cohort"
#' @param population_slug population, where a caveat depends on it
output_readme_caveats <- function(kind, population_slug = NULL) {

  common <- c(
    paste("Comorbidity (M3) was computed from index-admission diagnoses with",
          "no lookback period, so it under-counts pre-existing conditions and",
          "is not interpreted as a measure of multimorbidity."),
    paste("Deprivation was assigned at domicile level rather than SA1, which",
          "introduces misclassification against NZDep2023."),
    paste("ED disposition and time to clinician assessment were not available",
          "in the extract.")
  )

  by_kind <- switch(
    kind,
    tables = c(
      paste("Comparisons between ARISE-eligible and excluded patients are",
            "descriptive. Variables forming part of the eligibility criteria",
            "will differ by construction, and their p-values are not findings."),
      paste("Estimates for Maori and Asian patients rest on small numbers and",
            "carry wide intervals; they inform trial planning rather than",
            "supporting inference about ethnic differences in outcome.")),
    plots = c(
      paste("Bars show percentages within group with Wilson intervals, so",
            "groups of unequal size are comparable; the intervals are the",
            "guide to how much weight a bar carries."),
      paste("Dichotomous variables show the affirmative category only.")),
    regression = c(
      paste("Confidence intervals at the reported quantiles come from a",
            "bootstrap. Intervals elsewhere on the tau grid use a normal",
            "approximation and indicate the shape of the effect rather than",
            "supporting inference."),
      paste("A quantile contrast is a difference between group quantiles. It",
            "is not the effect on patients who sit at that quantile."),
      paste("Hollow points and daggered estimates mark a non-unique quantile",
            "regression solution: an interval of coefficients fits equally",
            "well and the reported value is one of them."),
      paste("Triage-adjusted models estimate a direct effect conditional on",
            "triage and are not comparable with the total effects reported",
            "elsewhere.")),
    daoh = c(
      paste("The count axis is transformed to make low counts visible, so the",
            "stacked segments are not drawn in proportion to their share."),
      paste("Lower quantiles of DAOH are not estimable where a large share of",
            "patients have no days at home; these are reported as such rather",
            "than omitted.")),
    cohort = character(0),
    character(0)
  )

  arise_note <- if (identical(population_slug, "arise_eligible"))
    paste("This folder covers only patients meeting the ARISE FLUIDS",
          "eligibility criteria, roughly half the severe sepsis cohort.",
          "Wider regression models were not fitted at this sample size.")
    else character(0)

  c(by_kind, arise_note, common)
}
